data = [
    {'name': 'Instagram', 'follower_count': 694, 'description': 'Social media platform', 'country': 'United States'},
    {'name': 'Cristiano Ronaldo', 'follower_count': 665, 'description': 'Footballer', 'country': 'Portugal'},
    {'name': 'Lionel Messi', 'follower_count': 507, 'description': 'Footballer', 'country': 'Argentina'},
    {'name': 'Selena Gomez', 'follower_count': 417, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Kylie Jenner', 'follower_count': 392, 'description': 'Reality TV personality and businesswoman', 'country': 'United States'},
    {'name': 'Dwayne Johnson', 'follower_count': 393, 'description': 'Actor and professional wrestler', 'country': 'United States'},
    {'name': 'Ariana Grande', 'follower_count': 374, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Kim Kardashian', 'follower_count': 355, 'description': 'Reality TV personality and businesswoman', 'country': 'United States'},
    {'name': 'Beyoncé', 'follower_count': 310, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Khloé Kardashian', 'follower_count': 301, 'description': 'Reality TV personality and businesswoman', 'country': 'United States'},
    {'name': 'Nike', 'follower_count': 299, 'description': 'Sportswear multinational', 'country': 'United States'},
    {'name': 'Justin Bieber', 'follower_count': 294, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'Virat Kohli', 'follower_count': 268, 'description': 'Cricketer', 'country': 'India'},
    {'name': 'Rihanna', 'follower_count': 267, 'description': 'Musician and businesswoman', 'country': 'Barbados'},
    {'name': 'Taylor Swift', 'follower_count': 237, 'description': 'Musician', 'country': 'United States'},
    {'name': 'David Beckham', 'follower_count': 233, 'description': 'Footballer', 'country': 'United Kingdom'},
    {'name': 'FC Barcelona', 'follower_count': 220, 'description': 'Football club', 'country': 'Spain'},
    {'name': 'NASA', 'follower_count': 189, 'description': 'Space agency', 'country': 'United States'},
    {'name': 'Shakira', 'follower_count': 188, 'description': 'Musician', 'country': 'Colombia'},
    {'name': 'Drake', 'follower_count': 165, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'LeBron James', 'follower_count': 163, 'description': 'Basketball player', 'country': 'United States'},
    {'name': 'Kendall Jenner', 'follower_count': 160, 'description': 'Reality TV personality and Model', 'country': 'United States'},
    {'name': 'Billie Eilish', 'follower_count': 158, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Kevin Hart', 'follower_count': 153, 'description': 'Comedian and actor', 'country': 'United States'},
    {'name': 'Ellen DeGeneres', 'follower_count': 149, 'description': 'Comedian', 'country': 'United States'},
    {'name': 'National Geographic', 'follower_count': 146, 'description': 'Magazine', 'country': 'United States'},
    {'name': 'Kourtney Kardashian', 'follower_count': 141, 'description': 'Reality TV personality', 'country': 'United States'},
    {'name': 'Kevin Hart', 'follower_count': 130, 'description': 'Comedian and actor', 'country': 'United States'},
    {'name': 'Real Madrid CF', 'follower_count': 120, 'description': 'Football club', 'country': 'Spain'}
]
